AllCops:
  DisabledByDefault: false
  TargetRubyVersion: 3.2
  DisplayCopNames: true
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'test/**/*'
    - 'bin/**/*'
    - 'spec/dummy_app/db/**/*'
  NewCops: enable

Security/YAMLLoad:
  Enabled: false

Layout/LineLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'paper_trail_scrapbook.gemspec'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'
